name: Cek cek

on:
  workflow_dispatch:
  schedule:
    - cron: '*/4 * * * *'

jobs:
  daily-cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          curl -sfL https://trakteer-scrapping.faultable.repl.co/ > /dev/null 2>&1
        env:
          SOME_ENV_VALUE: ${{ secrets.SOME_ENV_VALUE }}
